-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
require("config.keymaps")
require("config.options")
require("plugins.conform")
require("plugins.lsp")
require("plugins.telescope")
require("plugins.treescitter")
require("plugins.ui")
require("plugins.yazi")
